cat libHeader.js \
  event-manager.js \
  venn.js \
  utilities.js \
  attribute.js \
  viewer/word-cloud.js \
  viewer/scatterplot.js \
  viewer/histogram.js \
  viewer/variant-frequency.js \
  element-viewer.js \
  dataLoading.js \
  filter.js \
  selection.js \
  dataStructure.js \
  ui.js \
  setSelection.js \
  sort.js \
  highlight.js \
  scrollbar.js \
  items.js \
  setGrouping.js \
  logicPanel.js \
  brushableScale.js \
  statisticGraphs.js \
  upset.js \
  libFooter.js \
  > index.js
